export type Module = {
  id: number;
  title: string;
  duration: string;
  objective: string;
  concepts: { title: string; body: string }[];
  steps: string[];
  mistakes: string[];
  checklist: string[];
  resources?: { label: string; url: string }[];
};

export const modules: Module[] = [
  {
    id: 1,
    title: "The Rules of the Game",
    duration: "~20 min",
    objective: "Understand how ecommerce actually works before spending €1 — get the mindset and foundation right from day one.",
    concepts: [
      { title: "Your business is marketing, not your product", body: "Anyone can find a product. The people who win are the ones who get good at getting attention and converting it into sales." },
      { title: "Niche down, don't go wide", body: '"Fitness" is not a niche. "Home workouts for busy moms over 40" is a niche. The more specific you are, the less competition and the more passionate your buyers.' },
      { title: "You cannot compete on price", body: "Racing to be the cheapest kills your profit. You compete on value, story, and trust — not price." },
      { title: "There is no free traffic", body: "Organic and SEO take months. At the beginning, you pay for attention — either with money (ads) or time (TikTok content). Both cost something." },
      { title: "The 3X Rule", body: "Every product you sell must have at least 3× markup from what it costs you to what you sell it for. This pays for your ads, your time, and your profit." },
      { title: "Three ways to grow — and only three", body: "Get more customers. Get customers to spend more per order. Get customers to buy again. Every tactic you'll ever learn fits into one of these three." },
      { title: "The funnel beats the store", body: "A focused single-product page converts 3–5× better than a standard product listing page. You'll build one in Module 6." },
    ],
    steps: [
      "Read all 7 key concepts on this page",
      "Answer this honestly: What broad topic or hobby do you think you want to sell in?",
      "Answer this honestly: Who do you imagine buying from you?",
      "Answer this honestly: What is your rough starting budget? (No judgment — just be honest)",
      "Complete the checklist below and mark this module as complete",
    ],
    mistakes: [
      "Picking a product before you pick a niche",
      "Building a store before you validate a product",
      "Assuming your idea is unique — that's a trap",
      "Planning to compete on price",
      "Expecting free traffic to work quickly",
    ],
    checklist: [
      "I understand the 3X margin rule",
      "I understand there are only 3 ways to grow a business",
      "I know what a sales funnel is (a focused path from visitor to buyer)",
      "I have a rough niche idea to explore in Module 2",
      "I know my starting budget, even if it's small",
    ],
  },
  {
    id: 2,
    title: "Find Your Niche",
    duration: "~25 min",
    objective: "Choose one specific, passionate, profitable niche you'll build your entire business around.",
    concepts: [
      { title: "A niche is an audience, not a product", body: '"Dog owners" is a niche. "Dog collars" is a product. Always start with the people, not the thing.' },
      { title: "Passion niches outperform commodity niches", body: "People spend more money on things tied to their identity — fitness, pets, hobbies, parenting, sports." },
      { title: "Specific beats broad every time", body: '"Yoga" is too big. "Yoga for beginners over 50" is a niche you can actually win.' },
      { title: "Check for money, not just interest", body: "A niche needs paying customers, not just followers. If people aren't already spending money in this space, it's a hobby — not a business." },
    ],
    steps: [
      "Brainstorm 10 topics you personally know, love, or are curious about — write them down",
      'Filter using the 3-question test: Are people passionate about it? Do they already spend money on it? Can you find products with 3X margin?',
      "Google your top 3 ideas — do you see ads, stores, and active communities?",
      "Check Facebook Groups and Reddit for each — are people actively discussing and buying?",
      "Pick ONE niche and commit to it",
    ],
    mistakes: [
      'Picking a niche that\'s too broad (like "health and wellness")',
      "Picking a niche with no paying customers — too hobby-casual",
      "Switching niches before giving the first one a real try",
    ],
    checklist: [
      "I brainstormed at least 10 niche ideas",
      "I applied the 3-question filter to my top ideas",
      "I checked Google, Facebook Groups, and Reddit for my top ideas",
      "I have chosen ONE niche to move forward with",
    ],
  },
  {
    id: 3,
    title: "Find Your Winning Product",
    duration: "~30 min",
    objective: "Identify and validate one product to sell first — before spending any money on inventory.",
    concepts: [
      { title: "The 3X Rule is non-negotiable", body: "If your product costs €10 to land (buy + ship to you), you must sell it for at least €30. No exceptions. This covers ads, operations, and profit." },
      { title: "Validate before you buy", body: "Don't order 500 units until you know people want it. Use TikTok, Amazon, and Google to find proof of demand first." },
      { title: "One winning product beats ten average ones", body: "Focus on finding one great product, not building a full catalog. Depth beats breadth at the start." },
      { title: "Best product criteria", body: "Consumable or needs accessories (enables repeat purchases), passion-niche related, not at rock-bottom prices on Amazon, can be private-labeled later." },
    ],
    steps: [
      "Search your niche on AliExpress, TikTok Shop, and Amazon — what's already selling?",
      'Use TikTok\'s search bar: type your niche + "TikTok made me buy it" to find viral products',
      "Check Amazon Best Sellers in your niche category",
      "List 5 product candidates",
      "Apply the 3X Rule to each — eliminate any that don't pass",
      "Pick the one remaining product with the highest passion score",
      "Order one sample before committing to bulk inventory",
    ],
    mistakes: [
      "Falling in love with a product before validating demand",
      "Ignoring the 3X Rule because the product 'seems cool'",
      "Picking a product that's already a commodity on Amazon at €5",
    ],
    checklist: [
      "I found at least 5 product candidates in my niche",
      "I applied the 3X Rule and eliminated those that don't pass",
      "I checked TikTok and Amazon for proof of demand",
      "I have ONE product to move forward with",
      "I have ordered or planned to order a sample",
    ],
  },
  {
    id: 4,
    title: "Know Your Customer",
    duration: "~25 min",
    objective: "Build a detailed profile of exactly who you're selling to so every decision speaks directly to them.",
    concepts: [
      { title: "You are not the customer", body: "Your job is to understand someone else's desires, fears, and language — not your own. What matters is what they think, not what you think." },
      { title: "The more specific your avatar, the better everything converts", body: '"Women aged 28–45 who do yoga at home and feel guilty about skipping classes" beats "people who like yoga" every single time.' },
      { title: "People buy to feel something", body: "They buy solutions to problems, ways to feel proud, and things that match their identity. Understand the emotion behind the purchase." },
    ],
    steps: [
      "Write down your customer's basic profile: age range, gender, location, income level",
      "Answer the 7 emotional questions: What do they fear? What do they desire? What frustrates them? What makes them proud? What embarrasses them? What do they wish existed? What do they tell friends about?",
      "Find 3 real people who match this profile online (Reddit, Facebook Groups, Amazon reviews) and copy their exact words",
      "Write a one-paragraph story of your ideal customer — give them a name",
      "Save this avatar document — you'll use it in every module from here",
    ],
    mistakes: [
      "Skipping this step because it feels like homework",
      'Writing generic answers like "they want to save money" or "they want to be healthy"',
      "Forgetting to use their actual language in your copy and ads",
    ],
    checklist: [
      "I completed the basic demographic profile",
      "I answered all 7 emotional questions",
      "I found real customer language online (forums, reviews, groups)",
      "I wrote my customer avatar story with a name",
      "I saved my avatar document somewhere I can reference it",
    ],
  },
  {
    id: 5,
    title: "Build Your Shopify Store",
    duration: "~45 min",
    objective: "Launch a clean, professional-looking online store that builds trust and is ready to sell.",
    concepts: [
      { title: "Your store is your credibility", body: "A bad-looking store kills sales before the visitor even reads your product description. First impressions happen in under 3 seconds." },
      { title: "Simple wins", body: "You don't need 50 products. You need one great product page that builds trust and makes the buying decision easy." },
      { title: "Trust signals are everything", body: "Security badges, a clear return policy, real product photos, and customer reviews all convert visitors into buyers." },
      { title: "Mobile-first", body: "Over 70% of your visitors will see your store on a phone. Design for mobile, not desktop." },
    ],
    steps: [
      "Sign up for Shopify (free trial available at shopify.com)",
      "Choose the free 'Dawn' theme — clean and proven",
      "Set up your store name, logo (use Canva — free), and brand colors",
      "Add your hero product: great photos, a clear benefit-focused description, a strong price",
      "Set up payment methods (Shopify Payments or PayPal)",
      "Write and publish your Refund Policy, Privacy Policy, and Shipping Policy (Shopify generates these for you)",
      "Add trust badges to your product page",
      "Test your store on your phone — make sure it looks great",
    ],
    mistakes: [
      "Cluttered homepage with too many products",
      "Stock photos that look fake or low quality",
      "Missing policies — kills trust immediately",
      "No mobile testing before launching ads",
    ],
    checklist: [
      "Shopify store is live (even if not public yet)",
      "Hero product is added with good photos and a benefit-focused description",
      "Payment methods are set up and tested",
      "All three policies are published (Refund, Privacy, Shipping)",
      "Store looks clean and professional on mobile",
    ],
    resources: [
      { label: "Start Shopify free trial", url: "https://www.shopify.com" },
      { label: "Canva — free logo maker", url: "https://www.canva.com" },
    ],
  },
  {
    id: 6,
    title: "Build Your First Sales Funnel",
    duration: "~35 min",
    objective: "Create a focused, single-product landing page that converts 3–5× better than a standard store page.",
    concepts: [
      { title: "A funnel is a focused path", body: "No navigation menu. No distractions. One product, one decision: buy or leave. Every distraction you remove increases conversion." },
      { title: "The three parts of a basic funnel", body: "Landing page → Order bump at checkout → One upsell after payment. Each step adds revenue without needing more traffic." },
      { title: "The order bump adds ~21% more revenue", body: "A simple checkbox at checkout offering a complementary product for €5–15. Most people just tick it. It costs you nothing extra." },
      { title: "One-click upsell", body: "After they pay, offer a related product. They don't re-enter payment details — one click and it's added. Re-entry of details drops upsell conversion by 30%." },
    ],
    steps: [
      "Identify your hero product from Module 3",
      'Write your headline using this formula: [Specific Result] for [Specific Person] — Without [Common Fear]',
      "Create a landing page in Shopify: hero image or video, 3–5 bullet point benefits, customer reviews, clear Buy Now button",
      "Remove all navigation links from this page",
      "Set up one order bump: a complementary low-cost product (€5–15) as a checkbox at checkout",
      "Set up one upsell offer shown immediately after purchase",
      "Test the full flow yourself — place a test order and go through every step",
    ],
    mistakes: [
      "Keeping the navigation menu on the funnel page",
      'Writing features instead of benefits ("200ml bottle" vs. "enough for 30 days")',
      "Skipping the order bump — it's free money with zero extra traffic",
      "Making the upsell too expensive — keep it under 50% of the main product price",
    ],
    checklist: [
      "Stand-alone landing page is live",
      "Headline uses the benefit formula",
      "All navigation links removed from the funnel page",
      "Order bump is set up at checkout",
      "One upsell is set up after purchase",
      "Full funnel tested personally in test mode",
    ],
  },
  {
    id: 7,
    title: "Drive Traffic: TikTok Organic",
    duration: "~30 min",
    objective: "Get real eyes on your product for free using TikTok content — and learn what messaging works before spending money on ads.",
    concepts: [
      { title: "TikTok organic is the fastest free channel", body: "A single video can reach 100,000 people with zero ad spend. No other free platform gives beginners this reach in 2026." },
      { title: "You are making sales content, not art", body: "Every video has one job: get someone to click your link or search your brand. Entertainment is just the vehicle." },
      { title: "The hook is everything", body: "The first 2 seconds determines if people watch or scroll. Spend 80% of your creative effort on the opening line — not the rest of the video." },
      { title: "Post consistently, not perfectly", body: "1 video per day beats 1 perfect video per week every time. Volume creates learning. Learning creates winning content." },
    ],
    steps: [
      "Create a TikTok Business account and link your store in the bio",
      "Study the top 5 videos in your niche — note exactly what hooks they use in the first 2 seconds",
      'Film your first 3 video styles: "Problem → Solution", "Unboxing / reaction", "Before and after"',
      "Post one video per day for 2 weeks minimum",
      "Track views, profile visits, and link clicks for each video",
      "Double down on the format that gets the most link clicks",
    ],
    mistakes: [
      "Making videos that look like ads — they get scrolled past",
      "Giving up after 5 videos with low views",
      'Not adding a clear call to action: "link in bio to get yours"',
      "Posting without first studying what already works in your niche",
    ],
    checklist: [
      "TikTok Business account created and store linked in bio",
      "5 competitor videos studied and hooks noted",
      "First 3 videos filmed and posted",
      "Daily posting schedule set for at least 2 weeks",
      "Analytics checked after each video",
    ],
    resources: [
      { label: "TikTok Business Center", url: "https://business.tiktok.com" },
    ],
  },
  {
    id: 8,
    title: "Run Your First Paid Ad",
    duration: "~40 min",
    objective: "Launch your first small paid advertising campaign to drive targeted traffic to your funnel and get real data fast.",
    concepts: [
      { title: "Paid ads buy you speed and data", body: "Instead of waiting months for organic traffic, you pay to learn what works now. Think of your first ad budget as tuition — you're buying knowledge." },
      { title: "Start small and specific", body: "€20–30/day on one audience, one ad, one funnel. Do not spread your budget across multiple campaigns or products." },
      { title: "You are buying data first, sales second", body: "Your first campaign teaches you who buys and what message works. The goal is learning, not profit — profit comes after optimization." },
      { title: "Meta and TikTok Ads are the two best starting platforms", body: "Meta (Facebook/Instagram) has better targeting data. TikTok Ads have lower competition and cost. Pick one and start there." },
    ],
    steps: [
      "Choose your platform: Meta Ads or TikTok Ads — pick ONE, not both",
      "Install the pixel/tracking on your Shopify store (5-minute setup inside the platform)",
      "Create your first ad using your best-performing TikTok organic video",
      "Set your audience based on your customer avatar (age, interests, location)",
      "Set your daily budget: €20–30/day",
      "Run for 3–5 days without changing anything",
      "After 5 days, evaluate: cost per click, add-to-cart rate, purchase rate",
      "Turn off ads that spend €20+ with zero add-to-carts. Scale ads that produce purchases.",
    ],
    mistakes: [
      "Changing the campaign before it has enough data — minimum 3–5 days",
      "Running ads to your store homepage instead of your funnel",
      "Setting budget too low (under €15/day — not enough data to learn from)",
      "Using only image ads — video ads outperform by 3× on average",
    ],
    checklist: [
      "Ad account set up (Meta Business Manager or TikTok Ads Manager)",
      "Pixel/tracking installed and verified on Shopify store",
      "First ad created using video content",
      "Audience set based on customer avatar",
      "Campaign launched at €20–30/day",
      "First 5-day evaluation completed",
    ],
    resources: [
      { label: "Meta Business Manager", url: "https://business.facebook.com" },
      { label: "TikTok Ads Manager", url: "https://ads.tiktok.com" },
    ],
  },
  {
    id: 9,
    title: "Conversion Optimization",
    duration: "~30 min",
    objective: "Squeeze more sales out of the traffic you're already getting — without spending more on ads.",
    concepts: [
      { title: "Doubling conversion rate doubles revenue for free", body: "Most beginners focus only on getting more traffic. But improving conversion is faster and cheaper than buying more clicks." },
      { title: "Small changes make big differences", body: "A better headline, a review, a trust badge — each one can lift conversion by 5–20%. They compound." },
      { title: "The checkout is where most sales die", body: "Any friction at checkout — slow load, confusing layout, limited payment options — kills the sale at the last second." },
    ],
    steps: [
      "Add at least 5 real customer reviews to your product page (reach out to early buyers)",
      "Check page load speed on mobile using Google PageSpeed Insights — target under 3 seconds",
      "Ensure your Buy Now button is visible without scrolling on a phone",
      'Add a scarcity element: "Only 12 left in stock" or a limited-time offer',
      'Add a money-back guarantee badge: "30-day no-questions-asked return"',
      "A/B test your headline: run two versions for one week, keep the winner",
      "Set up cart abandonment email: automatically emails people who added to cart but didn't buy",
    ],
    mistakes: [
      "Adding too many pop-ups that interrupt the buying flow",
      "Fake scarcity — savvy shoppers notice and it destroys trust permanently",
      "No mobile testing after making changes",
      "Ignoring cart abandonment — 70% of carts are abandoned, recovering 5% is significant revenue",
    ],
    checklist: [
      "At least 5 real reviews visible on product page",
      "Mobile page speed checked and under 3 seconds",
      "Buy Now button visible above the fold on mobile",
      "At least one trust or guarantee badge added",
      "Cart abandonment email set up and tested",
    ],
  },
  {
    id: 10,
    title: "Build Your Email List",
    duration: "~35 min",
    objective: "Start collecting customer emails so you own a direct line to your audience — forever, for free.",
    concepts: [
      { title: "Your email list is the only traffic you truly own", body: "Social platforms can ban you overnight. Ad costs go up. But your email list cannot be taken away and costs nothing to send to." },
      { title: "Every buyer goes on your list automatically", body: "Past customers are 9× more likely to buy again than cold visitors. This is your most valuable and most ignored asset." },
      { title: "Your welcome sequence does the heavy lifting", body: "A 3–5 email series sent automatically after signup builds trust and drives repeat purchases — on autopilot." },
    ],
    steps: [
      "Sign up for Klaviyo — free up to 250 contacts, the industry standard for ecommerce",
      "Connect Klaviyo to your Shopify store",
      "Create a pop-up offering 10% off in exchange for an email address",
      "Write your 3-email welcome sequence: Email 1 (instant): welcome + discount. Email 2 (day 2): your brand story. Email 3 (day 4): social proof + best product + clear CTA",
      "Activate the cart abandonment flow (Klaviyo has a built-in template)",
      "Activate the post-purchase flow: thank you + ask for review + recommend a second product",
    ],
    mistakes: [
      "Only emailing people when you want to sell something — they unsubscribe",
      "Sending emails that look like spam — no images, bad formatting",
      'Not emailing consistently — "out of sight, out of mind"',
      "Skipping the welcome sequence — it has the highest open rates of any email you'll send",
    ],
    checklist: [
      "Klaviyo account created and connected to Shopify",
      "Email capture pop-up live on store",
      "3-email welcome sequence written and activated",
      "Cart abandonment flow activated",
      "Post-purchase flow activated",
    ],
    resources: [
      { label: "Sign up for Klaviyo (free)", url: "https://www.klaviyo.com" },
    ],
  },
  {
    id: 11,
    title: "Make Your First Sale",
    duration: "~20 min",
    objective: "Get your first real paying customer — and learn everything from the moment it happens.",
    concepts: [
      { title: "The first sale is proof of concept", body: "It means your product, your funnel, and your message are working. This is the most important milestone in ecommerce." },
      { title: "Analyze every detail of that first sale", body: "Where did they come from? Which ad? Which page? This data tells you exactly where to invest more money and time." },
      { title: "Fulfil it perfectly", body: "Your first customer's experience shapes your review, your repeat purchase rate, and your confidence. Treat them like gold." },
    ],
    steps: [
      "Confirm everything is live: funnel, payment, shipping setup, email flows",
      "Make sure your ad is running or your TikTok content is being posted daily",
      "Check your Shopify dashboard every morning",
      "When the first sale comes: manually confirm the order, ensure fulfilment is triggered",
      "Send a personal thank-you message to your first customer if possible",
      "After 7 days, review your data: what traffic source produced the sale? What was the conversion rate? Was there an order bump taken?",
      "Double down on whatever produced that first sale",
    ],
    mistakes: [
      "Panicking if the first sale doesn't come in week 1 — give it 2–3 weeks minimum",
      "Not tracking where the sale came from",
      "Changing your funnel or ads immediately after launch without enough data",
      "Ignoring the customer experience after the sale",
    ],
    checklist: [
      "All systems confirmed live: funnel, payment, shipping, and email flows",
      "Traffic is flowing: ad running or TikTok content posted daily",
      "First sale received and fulfilled perfectly",
      "Traffic source of first sale identified and noted",
      "Data reviewed: conversion rate, order bump rate, ad spend vs. revenue",
    ],
  },
  {
    id: 12,
    title: "Scale and Grow",
    duration: "~25 min",
    objective: "Understand the three levers of growth and take your first steps toward a sustainable, scaling ecommerce business.",
    concepts: [
      { title: "Three ways to grow — and only three", body: "More customers. Bigger orders. More repeat purchases. Every growth strategy you will ever encounter fits one of these three buckets." },
      { title: "Recurring income is the unlock", body: "Adding a subscription or replenishment offer to your business is worth 10× a one-time sale. It turns unpredictable income into reliable monthly revenue." },
      { title: "Scale what's working, not what looks exciting", body: "Your first successful product and funnel should be optimized deeply before you add a second product. Discipline here separates winners from hobbyists." },
    ],
    steps: [
      "Calculate your 60-day customer value: how much does the average buyer spend in their first 60 days?",
      "Add a subscription or replenishment option if your product is consumable",
      "Launch a second ad creative (different hook, same product) and test against your current winner",
      "Open a second sales channel: Amazon FBA or a second social platform",
      "Build a VIP customer segment in Klaviyo — anyone who has bought 2+ times gets special treatment",
      "Research your second product: it must serve the same avatar, complement the first product, and pass the 3X Rule",
    ],
    mistakes: [
      "Adding a second product before the first one is consistently profitable",
      "Ignoring existing customers while chasing new ones",
      "Scaling ad spend without improving conversion rate first",
      "Trying to be on every platform at once — two channels max for year one",
    ],
    checklist: [
      "60-day customer value calculated",
      "Subscription or replenishment option added if applicable",
      "Second ad creative tested",
      "VIP customer segment created in Klaviyo",
      "Second product researched and planned (not launched yet)",
    ],
  },
];

export function getModule(id: number): Module | undefined {
  return modules.find((m) => m.id === id);
}
